add Fragment Bottom Navigation
ZebanNikolay/dictionary pull request #32
Opened 2022-10-09 15:05 UTC by GenrikhsAlexandr

add Fragment Bottom Navigation

2022-10-10 05:59 UTC, ZebanNikolay requested changes

2022-10-10 05:59 UTC, ZebanNikolay commented on app/src/main/java/com/ncbs/dictionary/MainActivity.kt
> +                    )
У тебя тут скобки и выравнивание поехали. Можно делать это долго вручную или быстро с помощью команды  reformat code(поиском ее найди и там можно увидеть горячие клавиши)

2022-10-10 05:59 UTC, ZebanNikolay commented on app/src/main/java/com/ncbs/dictionary/MainActivity.kt
> +                else -> {
Можно написать else -> Unit. Будет короче запись и заодно прочитать, что такое Unit в Kotlin

2022-10-13 14:27 UTC, GenrikhsAlexandr commented on app/src/main/java/com/ncbs/dictionary/MainActivity.kt
> +                else -> {
> Можно написать else -> Unit. Будет короче запись и заодно прочитать, что такое Unit в Kotlin

Ставлю else -> Unit - выходит ошибка, ставлю else -> false - выходит ошибка

2022-10-16 07:20 UTC, ZebanNikolay approved these changes

2022-10-16 07:20 UTC, merged