Bottom sheet2
ZebanNikolay/dictionary pull request #55
Opened 2023-05-21 06:14 UTC by GenrikhsAlexandr

add lifecycleScope in WordDetailsBottomSheet
fix code in WordDetailsBottomSheet and home fragment

2023-05-21 07:47 UTC, ZebanNikolay requested changes

2023-05-21 07:47 UTC, ZebanNikolay commented on app/src/main/java/com/ncbs/dictionary/ui/WordDetailsBottomSheet.kt
> +            lifecycleScope.launch {
Тут launch не нужен, так как тут нету асинхроной работы

2023-05-21 07:47 UTC, ZebanNikolay commented on app/src/main/java/com/ncbs/dictionary/ui/activity/MainActivity.kt
> +        /*  binding.bottomNavigation.setupWithNavController(
Закомментированный код удаляй. Он не нужен в проекте тем более есть история гита

2023-05-21 07:47 UTC, ZebanNikolay commented on app/src/main/java/com/ncbs/dictionary/ui/home/HomeFragment.kt
> +            )
```
            val wordDetailsBottomSheet = WordDetailsBottomSheet(word)
            wordDetailsBottomSheet.show(
                parentFragmentManager,
                WordDetailsBottomSheet.TAG
            )
```
Вот этот весь код унеси в WordDetailsBottomSheet в companon object в функцию show(word: Word)
Что бы о деталях создания этого боттомщита знал только он сам а все остальные просто вызывали его функцию

2023-05-21 07:47 UTC, ZebanNikolay commented on app/src/main/res/layout/word_details_bottomsheet.xml
> -        style="@style/MaterialAlertDialog.Material3.Body.Text"
А по чему не заменил на textApperance?

2023-05-21 10:05 UTC, GenrikhsAlexandr commented on app/src/main/java/com/ncbs/dictionary/ui/home/HomeFragment.kt
> +            )
У меня не получается этот код  перенести, при нажатии на слово приложение падает.

2023-05-22 23:57 UTC, GenrikhsAlexandr commented on app/src/main/res/layout/word_details_bottomsheet.xml
> -        style="@style/MaterialAlertDialog.Material3.Body.Text"
У меня здесь был прописан  style и ниже textApperance. Я удалил style, а textApperance остался ниже.

2023-06-02 06:44 UTC, ZebanNikolay approved these changes

2023-06-02 06:44 UTC, ZebanNikolay commented on app/src/main/java/com/ncbs/dictionary/ui/WordDetailsBottomSheet.kt
> +        fun show(word: Word, fragment: FragmentManager) {
fragmentManager

2023-06-20 13:34 UTC, merged